"""Localization constants and helper functions for DD Manager."""

import json
import locale
import os


APP_VERSION = "v0.1.10"

LANGUAGE_CHOICES = [
    ("en", "English"),
    ("zh_CN", "简体中文"),
    ("pt_PT", "Português"),
    ("es_ES", "Español"),
]
LANGUAGE_CODE_TO_LABEL = dict(LANGUAGE_CHOICES)
LANGUAGE_LABEL_TO_CODE = {label: code for code, label in LANGUAGE_CHOICES}

TRANSLATIONS = {
    "en": {
        "app_title": "Darkest Dungeon Mod Manager",
        "app_subtitle": "Load Order Ledger",
        "startup_loading": "Loading save tools, profiles, and mod state...",
        "startup_stirring": "The hamlet is stirring...",
        "launch_game": "Launch Darkest Dungeon",
        "open_local_mods": "Open Local Mods",
        "file_paths": "File Paths",
        "auto_detect": "Auto Detect",
        "language": "Language:",
        "profile": "Profile:",
        "profile_none": "No profiles found",
        "refresh": "Refresh",
        "load_profile_mods": "Load Profile Mods",
        "patch_selected_profile": "Patch Selected Profile",
        "refresh_mods": "Refresh Mods",
        "save_loadout": "Save Loadout",
        "load_loadout": "Load Loadout",
        "tools": "Tools",
        "tool_patch_save": "Patch Chosen Save",
        "tool_patch_autodetected_legacy": "Patch Auto-Detected Save (Legacy)",
        "tool_generate_save_code": "Generate Save Code",
        "tool_apply_order": "Apply Order to Local Mods",
        "tool_restore_backup": "Restore Last Backup",
        "tool_check_setup": "Check Setup",
        "filter": "Filter:",
        "edit_categories": "Edit Categories",
        "category_editor_no_category": "No category",
        "category_editor_color": "Color: {color}",
        "category_editor_up": "Up",
        "category_editor_down": "Down",
        "category_editor_add": "Add",
        "category_editor_rename": "Rename",
        "category_editor_set_color": "Set Color",
        "category_editor_reset_color": "Reset Color",
        "category_editor_remove": "Remove",
        "category_editor_hint": "Built-in categories can be reordered. Custom categories can also be renamed or removed.",
        "search": "Search:",
        "view": "View:",
        "status_choose_mods": "Choose a mods folder or click Auto Detect.",
        "list_actions": "List Actions:",
        "auto_sort": "Auto Sort",
        "auto_categorize": "Auto Categorize",
        "nickname_mod": "Nickname Mod",
        "reserve": "Reserve",
        "enable_selected": "Enable >",
        "disable_selected": "< Reserve",
        "load_order": "Load Order",
        "status_selected_profile_save": "Selected profile save: {path}",
        "auto_detect_complete": "Auto Detect Complete",
        "nothing_found": "Nothing Found",
        "not_found": "Not found",
        "no_mod_folder_found": "No mod folder found",
        "no_save_file_found": "No save file found",
        "auto_detect_complete_body": "Game install:\n{game_root}\n\nLocal mods:\n{local_mods}\n\nWorkshop mods:\n{workshop_mods}\n\nActive mods source:\n{mod_text}\n\nLatest save:\n{save_text}\n\nProfiles found: {profile_count}",
        "auto_detect_nothing_found_body": "I could not auto-detect a Darkest Dungeon install, mods folder, or save file.\n\nUse File Paths to set the game, mods, or profile paths manually.",
        "startup_loading_mods_detected": "Loading mods from the detected folder...",
        "startup_scanning_profiles": "Scanning profile saves...",
        "status_loaded_mods_profiles": "Loaded mods from: {mods_path} | Profiles: {profile_count}",
        "startup_detecting_mods": "Detecting mods and preparing the load order...",
        "status_detected_game": "Detected game: {game_root} | Using mods: {mods_path} | Profiles: {profile_count}",
        "dd_detected": "Darkest Dungeon Detected",
        "dd_detected_body": "Game install:\n{game_root}\n\nLocal mods folder:\n{local_mods}\n\nWorkshop mods folder:\n{workshop_mods}\n\nUsing mods from:\n{mods_path}\n\nLatest save:\n{latest_save}\n\nProfiles found: {profile_count}",
        "status_no_dd_detected": "No Darkest Dungeon install was auto-detected. Open File Paths to set folders manually, then click Refresh Mods.",
        "select_persist_game": "Select persist.game.json",
        "darkest_dungeon_save": "Darkest Dungeon save",
        "json_files": "JSON files",
        "all_files": "All files",
        "status_manual_paths_profile": "Manual paths saved. Profile save: {path}",
        "status_manual_paths_mods": "Manual paths saved. Active mods folder: {path}",
        "status_manual_paths": "Manual paths saved.",
        "dialog_file_paths": "File Paths",
        "paths_editor_heading": "Edit the paths the app uses when auto-detect misses something.",
        "paths_editor_hint": "Leave a field blank to keep using auto-detect for that path.",
        "browse": "Browse",
        "auto": "Auto",
        "clear": "Clear",
        "save_file_paths": "Save File Paths",
        "cancel": "Cancel",
        "warning": "Warning",
        "select_one_mod_to_nickname": "Select exactly one mod to nickname.",
        "dialog_set_nickname": "Set Nickname",
        "nickname": "Nickname:",
        "save": "Save",
        "status_nickname_set": "Nickname set: {nickname}",
        "status_nickname_cleared": "Nickname cleared.",
        "error": "Error",
        "failed_save_nickname": "Failed to save nickname:\n\n{error}",
        "category_all": "All",
        "category_unassigned": "Unassigned",
        "category_ui": "UI",
        "category_districts": "Districts",
        "category_dungeons": "Dungeons",
        "category_quirks": "Quirks",
        "category_trinkets": "Trinkets",
        "category_enemies": "Enemies",
        "category_class_patch": "Class Patch",
        "category_class": "Class",
        "category_skins": "Skins",
        "category_builtin_suffix": "Built-in",
        "view_mode_no_icons": "No Icons",
        "view_mode_compact": "Compact",
        "view_mode_comfortable": "Comfortable",
        "view_mode_visual": "Visual",
        "status_mod_summary": "{enabled} enabled | {disabled} disabled | {uncategorized} uncategorized/new",
    },
    "zh_CN": {
        "app_title": "暗黑地牢模组管理器",
        "app_subtitle": "加载顺序概览",
        "startup_loading": "正在加载存档工具、档案和模组状态...",
        "startup_stirring": "村庄正在苏醒……",
        "launch_game": "启动《暗黑地牢》",
        "open_local_mods": "打开本地模组文件夹",
        "file_paths": "打开文件夹 / 选择路径",
        "auto_detect": "自动检测",
        "language": "语言：",
        "profile": "当前存档：",
        "profile_none": "未找到存档",
        "refresh": "刷新",
        "load_profile_mods": "加载已启用模组",
        "patch_selected_profile": "修补所选存档",
        "refresh_mods": "刷新模组",
        "save_loadout": "保存配置",
        "load_loadout": "加载配置",
        "tools": "工具",
        "tool_patch_save": "修补选定存档",
        "tool_patch_autodetected_legacy": "修补自动检测存档（旧版）",
        "tool_generate_save_code": "生成存档代码",
        "tool_apply_order": "应用顺序到本地模组",
        "tool_restore_backup": "恢复上次备份",
        "tool_check_setup": "检查设置",
        "filter": "筛选：",
        "edit_categories": "设置分类",
        "category_editor_no_category": "没有分类",
        "category_editor_color": "颜色：{color}",
        "category_editor_up": "上移",
        "category_editor_down": "下移",
        "category_editor_add": "添加",
        "category_editor_rename": "重命名",
        "category_editor_set_color": "设置颜色",
        "category_editor_reset_color": "重置颜色",
        "category_editor_remove": "删除",
        "category_editor_hint": "内建分类可以重新排序。自定义分类也可以在这里重命名或删除。",
        "search": "搜索：",
        "view": "视图：",
        "status_choose_mods": "请选择模组文件夹，或点击“自动检测”。",
        "list_actions": "列表操作：",
        "auto_sort": "自动排序",
        "auto_categorize": "自动分类",
        "nickname_mod": "设置昵称",
        "reserve": "备用",
        "enable_selected": "启用 >",
        "disable_selected": "< 备用",
        "load_order": "加载顺序",
        "status_selected_profile_save": "已选择存档：{path}",
        "auto_detect_complete": "自动检测完成",
        "nothing_found": "未找到内容",
        "not_found": "未找到",
        "no_mod_folder_found": "未找到模组文件夹",
        "no_save_file_found": "未找到存档文件",
        "auto_detect_complete_body": "游戏安装目录：\n{game_root}\n\n本地模组：\n{local_mods}\n\n创意工坊模组：\n{workshop_mods}\n\n当前模组来源：\n{mod_text}\n\n最新存档：\n{save_text}\n\n找到的存档数：{profile_count}",
        "auto_detect_nothing_found_body": "无法自动检测到 Darkest Dungeon 的安装目录、模组文件夹或存档文件。\n\n请使用“文件路径”手动设置游戏、模组或档案路径。",
        "startup_loading_mods_detected": "正在从检测到的文件夹加载模组...",
        "startup_scanning_profiles": "正在扫描存档...",
        "status_loaded_mods_profiles": "已从以下位置加载模组：{mods_path} | 存档数：{profile_count}",
        "startup_detecting_mods": "正在检测模组并准备加载顺序...",
        "status_detected_game": "已检测到游戏：{game_root} | 使用模组：{mods_path} | 存档数：{profile_count}",
        "dd_detected": "已检测到 Darkest Dungeon",
        "dd_detected_body": "游戏安装目录：\n{game_root}\n\n本地模组文件夹：\n{local_mods}\n\n创意工坊模组文件夹：\n{workshop_mods}\n\n当前使用模组：\n{mods_path}\n\n最新存档：\n{latest_save}\n\n找到的存档数：{profile_count}",
        "status_no_dd_detected": "未自动检测到 Darkest Dungeon。请打开“文件路径”手动设置文件夹，然后点击“刷新模组”。",
        "select_persist_game": "选择 persist.game.json",
        "darkest_dungeon_save": "Darkest Dungeon 存档",
        "json_files": "JSON 文件",
        "all_files": "所有文件",
        "status_manual_paths_profile": "已保存手动路径。存档：{path}",
        "status_manual_paths_mods": "已保存手动路径。当前模组文件夹：{path}",
        "status_manual_paths": "已保存手动路径。",
        "dialog_file_paths": "文件路径",
        "paths_editor_heading": "当自动检测没有命中时，可在这里修改应用使用的路径。",
        "paths_editor_hint": "将字段留空即可继续对此路径使用自动检测。",
        "browse": "浏览",
        "auto": "自动",
        "clear": "清除",
        "save_file_paths": "保存文件路径",
        "cancel": "取消",
        "warning": "警告",
        "select_one_mod_to_nickname": "请选择且仅选择一个模组来设置昵称。",
        "dialog_set_nickname": "设置昵称",
        "nickname": "昵称：",
        "save": "保存",
        "status_nickname_set": "已设置昵称：{nickname}",
        "status_nickname_cleared": "已清除昵称。",
        "error": "错误",
        "failed_save_nickname": "保存昵称失败：\n\n{error}",
        "category_all": "全部",
        "category_unassigned": "未分类",
        "category_ui": "界面",
        "category_districts": "城镇建筑",
        "category_dungeons": "地牢",
        "category_quirks": "怪癖",
        "category_trinkets": "饰品",
        "category_enemies": "敌人",
        "category_class_patch": "职业补丁",
        "category_class": "职业",
        "category_skins": "皮肤",
        "category_builtin_suffix": "内建",
        "view_mode_no_icons": "无图标",
        "view_mode_compact": "紧凑",
        "view_mode_comfortable": "舒适",
        "view_mode_visual": "视觉模式",
        "status_mod_summary": "{enabled} 已启用 | {disabled} 已禁用 | {uncategorized} 未分类 / 新增",
    },
    "pt_PT": {
        "app_title": "Gestor de Mods Darkest Dungeon",
        "app_subtitle": "Registo da Ordem de Carregamento",
        "startup_loading": "A carregar ferramentas de gravação, perfis e estado dos mods...",
        "startup_stirring": "A aldeia está a despertar...",
        "launch_game": "Iniciar Darkest Dungeon",
        "open_local_mods": "Abrir Mods Locais",
        "file_paths": "Caminhos de Ficheiros",
        "auto_detect": "Deteção Automática",
        "language": "Idioma:",
        "profile": "Perfil:",
        "profile_none": "Nenhum perfil encontrado",
        "refresh": "Atualizar",
        "load_profile_mods": "Carregar Mods do Perfil",
        "patch_selected_profile": "Aplicar ao Perfil Selecionado",
        "refresh_mods": "Atualizar Mods",
        "save_loadout": "Guardar Configuração",
        "load_loadout": "Carregar Configuração",
        "tools": "Ferramentas",
        "tool_patch_save": "Aplicar à Gravação Escolhida",
        "tool_patch_autodetected_legacy": "Aplicar à Gravação Detetada Automaticamente (Legado)",
        "tool_generate_save_code": "Gerar Código de Gravação",
        "tool_apply_order": "Aplicar Ordem aos Mods Locais",
        "tool_restore_backup": "Restaurar Última Cópia de Segurança",
        "tool_check_setup": "Verificar Configuração",
        "filter": "Filtro:",
        "edit_categories": "Editar Categorias",
        "category_editor_no_category": "Sem categoria",
        "category_editor_color": "Cor: {color}",
        "category_editor_up": "Subir",
        "category_editor_down": "Descer",
        "category_editor_add": "Adicionar",
        "category_editor_rename": "Renomear",
        "category_editor_set_color": "Definir Cor",
        "category_editor_reset_color": "Repor Cor",
        "category_editor_remove": "Remover",
        "category_editor_hint": "As categorias integradas podem ser reordenadas. As categorias personalizadas também podem ser renomeadas ou removidas.",
        "search": "Pesquisar:",
        "view": "Vista:",
        "status_choose_mods": "Escolha uma pasta de mods ou clique em Deteção Automática.",
        "list_actions": "Ações da Lista:",
        "auto_sort": "Ordenação Automática",
        "auto_categorize": "Categorização Automática",
        "nickname_mod": "Dar Alcunha ao Mod",
        "reserve": "Reserva",
        "enable_selected": "Ativar >",
        "disable_selected": "< Reserva",
        "load_order": "Ordem de Carregamento",
        "status_selected_profile_save": "Gravação de perfil selecionada: {path}",
        "auto_detect_complete": "Deteção Automática Concluída",
        "nothing_found": "Nada Encontrado",
        "not_found": "Não encontrado",
        "no_mod_folder_found": "Nenhuma pasta de mods encontrada",
        "no_save_file_found": "Nenhum ficheiro de gravação encontrado",
        "auto_detect_complete_body": "Instalação do jogo:\n{game_root}\n\nMods locais:\n{local_mods}\n\nMods da Workshop:\n{workshop_mods}\n\nOrigem ativa dos mods:\n{mod_text}\n\nÚltima gravação:\n{save_text}\n\nPerfis encontrados: {profile_count}",
        "auto_detect_nothing_found_body": "Não foi possível detetar automaticamente uma instalação de Darkest Dungeon, pasta de mods ou ficheiro de gravação.\n\nUse Caminhos de Ficheiros para definir manualmente os caminhos do jogo, dos mods ou dos perfis.",
        "startup_loading_mods_detected": "A carregar mods da pasta detetada...",
        "startup_scanning_profiles": "A procurar gravações de perfil...",
        "status_loaded_mods_profiles": "Mods carregados de: {mods_path} | Perfis: {profile_count}",
        "startup_detecting_mods": "A detetar mods e a preparar a ordem de carregamento...",
        "status_detected_game": "Jogo detetado: {game_root} | A usar mods: {mods_path} | Perfis: {profile_count}",
        "dd_detected": "Darkest Dungeon Detetado",
        "dd_detected_body": "Instalação do jogo:\n{game_root}\n\nPasta de mods locais:\n{local_mods}\n\nPasta de mods da Workshop:\n{workshop_mods}\n\nA usar mods de:\n{mods_path}\n\nÚltima gravação:\n{latest_save}\n\nPerfis encontrados: {profile_count}",
        "status_no_dd_detected": "Nenhuma instalação de Darkest Dungeon foi detetada automaticamente. Abra Caminhos de Ficheiros para definir as pastas manualmente e depois clique em Atualizar Mods.",
        "select_persist_game": "Selecionar persist.game.json",
        "darkest_dungeon_save": "Gravação de Darkest Dungeon",
        "json_files": "Ficheiros JSON",
        "all_files": "Todos os ficheiros",
        "status_manual_paths_profile": "Caminhos manuais guardados. Gravação de perfil: {path}",
        "status_manual_paths_mods": "Caminhos manuais guardados. Pasta ativa de mods: {path}",
        "status_manual_paths": "Caminhos manuais guardados.",
        "dialog_file_paths": "Caminhos de Ficheiros",
        "paths_editor_heading": "Edite os caminhos que a aplicação usa quando a deteção automática falha.",
        "paths_editor_hint": "Deixe um campo em branco para continuar a usar a deteção automática nesse caminho.",
        "browse": "Procurar",
        "auto": "Automático",
        "clear": "Limpar",
        "save_file_paths": "Guardar Caminhos de Ficheiros",
        "cancel": "Cancelar",
        "warning": "Aviso",
        "select_one_mod_to_nickname": "Selecione exatamente um mod para lhe dar uma alcunha.",
        "dialog_set_nickname": "Definir Alcunha",
        "nickname": "Alcunha:",
        "save": "Guardar",
        "status_nickname_set": "Alcunha definida: {nickname}",
        "status_nickname_cleared": "Alcunha removida.",
        "error": "Erro",
        "failed_save_nickname": "Falha ao guardar a alcunha:\n\n{error}",
        "category_all": "Todos",
        "category_unassigned": "Sem Categoria",
        "category_ui": "Interface",
        "category_districts": "Distritos",
        "category_dungeons": "Masmorras",
        "category_quirks": "Manias",
        "category_trinkets": "Bugigangas",
        "category_enemies": "Inimigos",
        "category_class_patch": "Patch de Classe",
        "category_class": "Classe",
        "category_skins": "Visuais",
        "category_builtin_suffix": "Integrada",
        "view_mode_no_icons": "Sem Ícones",
        "view_mode_compact": "Compacto",
        "view_mode_comfortable": "Confortável",
        "view_mode_visual": "Visual",
        "status_mod_summary": "{enabled} ativados | {disabled} desativados | {uncategorized} sem categoria/novos",
    },
    "es_ES": {
        "app_title": "Administrador de Mods de Darkest Dungeon",
        "app_subtitle": "Registro del Orden de Carga",
        "startup_loading": "Cargando herramientas de guardado, perfiles y estado de mods...",
        "startup_stirring": "La aldea está despertando...",
        "launch_game": "Iniciar Darkest Dungeon",
        "open_local_mods": "Abrir Mods Locales",
        "file_paths": "Rutas de Archivos",
        "auto_detect": "Detección Automática",
        "language": "Idioma:",
        "profile": "Perfil:",
        "profile_none": "No se encontraron perfiles",
        "refresh": "Actualizar",
        "load_profile_mods": "Cargar Mods del Perfil",
        "patch_selected_profile": "Aplicar al Perfil Seleccionado",
        "refresh_mods": "Actualizar Mods",
        "save_loadout": "Guardar Configuración",
        "load_loadout": "Cargar Configuración",
        "tools": "Herramientas",
        "tool_patch_save": "Aplicar al Guardado Elegido",
        "tool_patch_autodetected_legacy": "Aplicar al Guardado Detectado Automáticamente (Legado)",
        "tool_generate_save_code": "Generar Código de Guardado",
        "tool_apply_order": "Aplicar Orden a los Mods Locales",
        "tool_restore_backup": "Restaurar la Última Copia de Seguridad",
        "tool_check_setup": "Comprobar Configuración",
        "filter": "Filtro:",
        "edit_categories": "Editar Categorías",
        "category_editor_no_category": "Sin categoría",
        "category_editor_color": "Color: {color}",
        "category_editor_up": "Subir",
        "category_editor_down": "Bajar",
        "category_editor_add": "Añadir",
        "category_editor_rename": "Renombrar",
        "category_editor_set_color": "Asignar Color",
        "category_editor_reset_color": "Restablecer Color",
        "category_editor_remove": "Eliminar",
        "category_editor_hint": "Las categorías integradas se pueden reordenar. Las categorías personalizadas también se pueden renombrar o eliminar.",
        "search": "Buscar:",
        "view": "Vista:",
        "status_choose_mods": "Elige una carpeta de mods o haz clic en Detección Automática.",
        "list_actions": "Acciones de la Lista:",
        "auto_sort": "Ordenación Automática",
        "auto_categorize": "Categorización Automática",
        "nickname_mod": "Poner Apodo al Mod",
        "reserve": "Reserva",
        "enable_selected": "Activar >",
        "disable_selected": "< Reserva",
        "load_order": "Orden de Carga",
        "status_selected_profile_save": "Guardado de perfil seleccionado: {path}",
        "auto_detect_complete": "Detección Automática Completada",
        "nothing_found": "No se Encontró Nada",
        "not_found": "No encontrado",
        "no_mod_folder_found": "No se encontró ninguna carpeta de mods",
        "no_save_file_found": "No se encontró ningún archivo de guardado",
        "auto_detect_complete_body": "Instalación del juego:\n{game_root}\n\nMods locales:\n{local_mods}\n\nMods de Workshop:\n{workshop_mods}\n\nOrigen activo de mods:\n{mod_text}\n\nÚltimo guardado:\n{save_text}\n\nPerfiles encontrados: {profile_count}",
        "auto_detect_nothing_found_body": "No se pudo detectar automáticamente una instalación de Darkest Dungeon, una carpeta de mods o un archivo de guardado.\n\nUsa Rutas de Archivos para establecer manualmente las rutas del juego, los mods o los perfiles.",
        "startup_loading_mods_detected": "Cargando mods desde la carpeta detectada...",
        "startup_scanning_profiles": "Buscando guardados de perfil...",
        "status_loaded_mods_profiles": "Mods cargados desde: {mods_path} | Perfiles: {profile_count}",
        "startup_detecting_mods": "Detectando mods y preparando el orden de carga...",
        "status_detected_game": "Juego detectado: {game_root} | Usando mods: {mods_path} | Perfiles: {profile_count}",
        "dd_detected": "Darkest Dungeon Detectado",
        "dd_detected_body": "Instalación del juego:\n{game_root}\n\nCarpeta de mods locales:\n{local_mods}\n\nCarpeta de mods de Workshop:\n{workshop_mods}\n\nUsando mods desde:\n{mods_path}\n\nÚltimo guardado:\n{latest_save}\n\nPerfiles encontrados: {profile_count}",
        "status_no_dd_detected": "No se detectó automáticamente ninguna instalación de Darkest Dungeon. Abre Rutas de Archivos para establecer las carpetas manualmente y luego haz clic en Actualizar Mods.",
        "select_persist_game": "Seleccionar persist.game.json",
        "darkest_dungeon_save": "Guardado de Darkest Dungeon",
        "json_files": "Archivos JSON",
        "all_files": "Todos los archivos",
        "status_manual_paths_profile": "Rutas manuales guardadas. Guardado de perfil: {path}",
        "status_manual_paths_mods": "Rutas manuales guardadas. Carpeta activa de mods: {path}",
        "status_manual_paths": "Rutas manuales guardadas.",
        "dialog_file_paths": "Rutas de Archivos",
        "paths_editor_heading": "Edita las rutas que usa la aplicación cuando la detección automática no encuentra algo.",
        "paths_editor_hint": "Deja un campo vacío para seguir usando la detección automática en esa ruta.",
        "browse": "Examinar",
        "auto": "Automático",
        "clear": "Borrar",
        "save_file_paths": "Guardar Rutas de Archivos",
        "cancel": "Cancelar",
        "warning": "Advertencia",
        "select_one_mod_to_nickname": "Selecciona exactamente un mod para ponerle un apodo.",
        "dialog_set_nickname": "Definir Apodo",
        "nickname": "Apodo:",
        "save": "Guardar",
        "status_nickname_set": "Apodo definido: {nickname}",
        "status_nickname_cleared": "Apodo eliminado.",
        "error": "Error",
        "failed_save_nickname": "No se pudo guardar el apodo:\n\n{error}",
        "category_all": "Todos",
        "category_unassigned": "Sin Clasificar",
        "category_ui": "Interfaz",
        "category_districts": "Distritos",
        "category_dungeons": "Mazmorras",
        "category_quirks": "Rarezas",
        "category_trinkets": "Abalorios",
        "category_enemies": "Enemigos",
        "category_class_patch": "Parche de Clase",
        "category_class": "Clase",
        "category_skins": "Aspectos",
        "category_builtin_suffix": "Integrada",
        "view_mode_no_icons": "Sin Iconos",
        "view_mode_compact": "Compacto",
        "view_mode_comfortable": "Cómodo",
        "view_mode_visual": "Visual",
        "status_mod_summary": "{enabled} activados | {disabled} desactivados | {uncategorized} sin clasificar/nuevos",
    },
}

CATEGORY_TRANSLATION_KEYS = {
    "All": "category_all",
    "Unassigned": "category_unassigned",
    "UI": "category_ui",
    "Districts": "category_districts",
    "Dungeons": "category_dungeons",
    "Quirks": "category_quirks",
    "Trinkets": "category_trinkets",
    "Enemies": "category_enemies",
    "Class Patch": "category_class_patch",
    "Class": "category_class",
    "Skins": "category_skins",
}

VIEW_MODE_TRANSLATION_KEYS = {
    "No Icons": "view_mode_no_icons",
    "Compact": "view_mode_compact",
    "Comfortable": "view_mode_comfortable",
    "Visual": "view_mode_visual",
}


def translate_text(language, key, **kwargs):
    template = TRANSLATIONS.get(language, {}).get(key)
    if template is None:
        template = TRANSLATIONS["en"].get(key, key)
    try:
        return template.format(**kwargs)
    except Exception:
        return template


def map_locale_to_language(locale_name):
    normalized = str(locale_name or "").strip().lower().replace("-", "_")
    if normalized.startswith("zh"):
        return "zh_CN"
    if normalized.startswith("pt"):
        return "pt_PT"
    if normalized.startswith("es"):
        return "es_ES"
    return "en"


def detect_default_language(is_windows, ctypes_module):
    if is_windows and ctypes_module is not None:
        try:
            language_id = ctypes_module.windll.kernel32.GetUserDefaultUILanguage()
            windows_locale_name = locale.windows_locale.get(language_id, "")
            detected = map_locale_to_language(windows_locale_name)
            if detected != "en" or windows_locale_name:
                return detected
        except Exception:
            pass

    for locale_name in (
        locale.getlocale()[0],
        os.environ.get("LANG"),
        os.environ.get("LC_ALL"),
        os.environ.get("LC_MESSAGES"),
    ):
        if locale_name:
            return map_locale_to_language(locale_name)

    return "en"


def read_saved_language(state_file, is_windows, ctypes_module):
    default_language = detect_default_language(is_windows, ctypes_module)
    if not os.path.exists(state_file):
        return default_language
    try:
        with open(state_file, "r", encoding="utf-8") as f:
            state = json.load(f)
        return state.get("language", default_language)
    except Exception:
        return default_language


def subtitle_with_version(text):
    return f"{text} {APP_VERSION}"
